### ISSUE TITLE
paths in python; Where to download Python for Biologists exercises

### ISSUE THREAD

**Issue by chriscast123** [eeb177-W17/eeb177-W17.github.io#22]
Hello, so for HW#4 part 3 is asking to extract files provided by the Python for Biologists.  One file called "input.txt" but it's not finding it. The error message says FileNotFoundError: [Errno 2] No such file or directory: 'input.txt'

I have all my Python for Biologists files under the homework directory in virtual box and also where my other homework assignments from past weeks are located. What can I do to fix this problem?

**Comment by onnysmu3** [comment]
I think it happens since we have no access to download Chapter 3 and Chapter 4 folder. We could actually have an access to download it when we buy Python for Biologist book, but we unfortunately got the book by free instead of buying it. 

Is it the problem? 

If YES, my question is how we can get an access to download Chapter 3 and Chapter 4 folder. I tried looking for an access to the folders on Google, but there is no result for that. Does anyone have an access to the folders?

**Comment by chriscast123** [comment]
This is where I downloaded them from.
http://pythonforbiologists.com/index.php/exercise-files/
