### ISSUE TITLE
Problem with Formatted data - hw5

### ISSUE THREAD

**Issue by erinsolis29** [eeb177-W17/eeb177-W17.github.io#25]
In class, I was following along with Professor Alfaro and made the new formatted nature csv file.  However, when I did the head command on the new formatted file,  a bunch of random symbols show up instead of the actual data. I re-downloaded the file and tried to run the commands again, and it still did the same thing. Any suggestions on how to fix this?

**Comment by gauravsk** [comment]
@erinsolis29 please give exact commands- this shouldn't be happening.

**Comment by erinsolis29** [comment]
download files
cat filename.csv | tr "\r" "\n" > formattedfilename.csv
wc -l formattedfilename.csv
head formattedfilename.csv

**Comment by gauravsk** [comment]
How are you downloading the files?

**Comment by erinsolis29** [comment]
directly from the website.
when i do it from the terminal with 'wget', i get an error message saying "no certificate subject alternative name matches"

**Comment by tdaang** [comment]
Yeah, I had the same problem as well. It's the same problem I showed you on thursday when I got a bunch of random symbols and you suggested to redownload the file since it might've just been a corrupted version, but when I downloaded it again, the symbols popped up again. When I did wc -l, I was able to get a number count but when I used the head command, the symbols showed up

**Comment by gauravsk** [comment]
Strange. Let's take a look tomorrow.
