### ISSUE TITLE
cut: option requires an argument -- 'f'

### ISSUE THREAD

**Issue by chriscast123** [eeb177-W17/eeb177-W17.github.io#5]
I'm having trouble how to through this step for the hw. I insert the command: $ tail -n +2 ../data/Pacifici2013_data.csv | cut -d ’;’ -f     and the output comes out saying that cut: option requires an argument -- 'f'

I have no idea how to proceed with this I'm following the book but it doesn't seem to help you out when you encounter this problem. How can I proceed?

**Comment by gauravsk** [comment]
@chriscast123 can you please clarify which exercise in CSB text this refers to? Use the line and page numbers for reference.

**Comment by pprbckwrtr** [comment]
It says that because -f refers to the "column". So -d ";" is saying to take every instance of a semicolon as a column separator, and -f is saying which column to refer to. So if you're looking for families, the header for the Pacific-whatever file will say something like taxid; order; family etc and that means family is the 3rd column, so you would put -f 3
